### ISSUE TITLE
Report range problem

### ISSUE THREAD

**Issue by mark2045** [martinm76/zabbix-pdf-report#1]
Hello, Martinm76!

After last update to 1.0.1 Custom Report range isn't work. When I choose period 01/09/2018-01/10/2018 in Debug mode we see that it take period range - last 1 hour. Could you fix?

![image](https://user-images.githubusercontent.com/44284453/47199232-65b75600-d392-11e8-88de-ab3114da0585.png)

**Comment by martinm76** [comment]
Hey Mark.
From what I have gathers with another user, this is related to the way Zabbix 4.x generates graphs and it would seem they have changed the parameters I need to send. I'll look into this when I have Zabbix 4.0.1 installed on my test system.

**Comment by martinm76** [comment]
Hey Mark.

I have now managed to debug the issue in my test environment om Zabbix 4.0. The graphing has changed a lot (although the output is basically the same for our purposes).

I have attached a patch that should work on 4.0. I have yet to test that is doesn't break something in Zabbix 3.4 so not committed yet. Can you confirm it works for you?

Not only have they changed from stime and period to from and to, I also have to include ProfileIdx=web.graphs.filter for it to event respect the from and to values. Not sure why that is, but this seems to work here.

[zabbix-40-graphs.patch.txt](https://github.com/martinm76/zabbix-pdf-report/files/2498524/zabbix-40-graphs.patch.txt)

**Comment by amarodefarias** [comment]
Hello.

Where should I put this file?
Should it be renamed to createpdf.functions.php? I am waiting for the instructions to carry out the tests.

Thank you

**Comment by martinm76** [comment]
Hi Mark.

Copy zabbix-40-graphs.patch.txt to the 'inc' dir of your installation. cd to the 'inc' dir of your installation.
Run this command:
patch <zabbix-40-graphs.patch.txt

That should update createpdf.functions.php at your end to be the same as mine, given you havent't manually changed the file. After that, the graphs ought to work.

**Comment by amarodefarias** [comment]
Hi. Thanks a lot for the help, you understand a lot! It must have taken a lot of work to do this, but know that it was worth it! It worked perfectly here.

Success!

**Comment by martinm76** [comment]
The fix has been mainlined and also tested on 3.4 - it still works (with the old syntax also given). Closing the issue.
