### ISSUE TITLE
zabbix pdf generation using curl command 

### ISSUE THREAD

**Issue by Pranesh1114** [martinm76/zabbix-pdf-report#10]
how to generate zabbix dynamic pdf report via curl command

**Comment by martinm76** [comment]
You can do something like this:
`curl -L -o ZabbixServer.pdf 'http://localhost/report/createpdf.php?ReportType=host&HostID=10084&GroupID=&GraphsOn=yes&ItemGraphsOn=yes&TriggersOn=yes&ItemsOn=yes&TrendsOn=yes&mygraphs2=%23%28Ping%7CCPU+load%7CCPU+usage%7CCPU+util%7Cprocessor%7CDisk+space%7CSwap%7CEthernet%7CMemory+usage%7C%5ETraffic+on+%7Ctraffic+on+eth%29%23&myitems2=%23%28Utilization+of%7Cfarm+connection%7CAverage+Latency%7CNumber+of+processes%7CCache+%25+Hit%29%23&ReportRange=last&timePeriod=Week&startdate=&starttime=&enddate=&endtime='
`
^-> That is ONE line.

Get the request you want from the access_log and set the filename after -o to what you want the report to be called. You need to add either http://localhost or https://localhost to the URL, assuming you have installed the report in /report from the base URL of the webserver.
