### ISSUE TITLE
No data shown in graph

### ISSUE THREAD

**Issue by gopalraha** [martinm76/zabbix-pdf-report#11]
Hi there,

I have deployed the same in Zabbix 5.0 it is deployed successfully but no data shown in graph 

please check our setup http://172.105.55.24/zbxreport/chooser.php and report http://172.105.55.24/zbxreport/reports/Wordpress.pdf

Please fix this issue https://raw.githubusercontent.com/gopalraha/spartan/master/Capture.PNG

Thanks a lot.

**Comment by martinm76** [comment]
Looks mostly like Zabbix is not actually getting any data. Show me the same graph from Zabbix with data in it, please.

**Comment by gopalraha** [comment]
Hi Martin,

Thanks for response.

Zabbix is getting data.

Please login to my zabbix portal and check the data.

http://172.105.55.24/zabbix/

Username: Admin
Password: zabbix

please feel free to check it and let me know what is the issue.

Thanks and regards
Gopal Raha

**Comment by martinm76** [comment]
The site does not seem repsonsive right now.

**Comment by martinm76** [comment]
Haven't received further followup and cannot reproduce.
