### ISSUE TITLE
PHP Warning - Unable to establish API call

### ISSUE THREAD

**Issue by tech-novic** [martinm76/zabbix-pdf-report#18]
PHP Warning: get_class() expects parameter 1 to be object, null given in /usr/share/zabbix/zabbix-pdf-report/inc/ZabbixAPI.class.php on line 208, referer: http://zabbix-server/zabbix/zabbix-pdf-report/chooser.php

**Comment by martinm76** [comment]
What version are you running?

**Comment by martinm76** [comment]
No reply in roughly two months, closing the issue.
