### ISSUE TITLE
Error in php and curl exits in zabbix-pdf-report index

### ISSUE THREAD

**Issue by leandrosraphael** [martinm76/zabbix-pdf-report#25]
First of all I would like to thank you for the tool, and I would like to clarify a question, I am using zabbix 5.2.5, and php 7.4 and configured the zabbix-report, but on the main screen as soon as we log in it appears some curl outputs, and when I go in the php error log it shows the following error:
[Tue Apr 13 18:25:53.571098 2021] [php7:warn] [pid 445685] [client 10.0.0.239:62357] PHP Warning:  get_class() expects parameter 1 to be object, null given in /usr/share/zabbix-pdf-report/inc/ZabbixAPI.class.php on line 208, referer: http://zabbix2.portosrio.gov.br/zbxreport/index.php

Can anybody help me?

Error that appears as soon as I log in.
![image](https://user-images.githubusercontent.com/27435132/114606475-acd7e680-9c71-11eb-8028-2d41dcca5d08.png)

since already my thanks

**Comment by martinm76** [comment]
Have you set the version of Zabbix in config.inc.php to 5.0 or higher?
This looks like the 'bug' that was 'fixed' in 5.0 and later and some of the last versions of 4.4

**Comment by leandrosraphael** [comment]
Yes, I put 5.0, but the error was only corrected, when I deactivated the debugs, which were true, after that, everything worked.

And thanks for answering me and trying to help me.

The tool is incredible.
