### ISSUE TITLE
project working on 5.2?

### ISSUE THREAD

**Issue by killmasta93** [martinm76/zabbix-pdf-report#26]
Hi is this project still working for zabbix 5.2?

**Comment by lptarik** [comment]
We are using 5.4 . It would be greate if it worked. Zabbix's new report feature sucks :)

**Comment by ironbishop** [comment]
personally i will not use 5.2 or 5.4 and only upgrade to 6.0 when available

**Comment by martinm76** [comment]
I'm using it just fine on 5.4, so I ask again if you have set the version in config.ini.php? I'm thinking of switching the defaults around, since it seems 4.4.x also eliminated the need to call with debugging.
Please post an error message or screenshot of it not working.

**Comment by lptarik** [comment]
Yes ıt is working all seems fine.thanks
