### ISSUE TITLE
Zabbix-pdf-report/inc/ZabbixAPI.class.php on line 324

### ISSUE THREAD

**Issue by FlanniganColum** [martinm76/zabbix-pdf-report#28]
I get the below error when i try and login to the pdf report section. All i done was clone the report into the usr/share/zabbix directory copied the config template to the config file "cp config.inc.php.dist config.inc.php" changed the zabbix url and tested the login..

Any idea what could have caused this??

[Thu Apr 21 09:56:58.501547 2022] [php7:error] [pid 67887] [client XX.XX.XX.XX:52854] PHP Fatal error:  Uncaught Error: Call to undefined function curl_init() in /usr/share/zabbix/zabbix-pdf-report/inc/ZabbixAPI.class.php:324\nStack trace:\n#0 /usr/share/zabbix/zabbix-pdf-report/inc/ZabbixAPI.class.php(257): ZabbixAPI::__jsonRequest()\n#1 /usr/share/zabbix/zabbix-pdf-report/inc/ZabbixAPI.class.php(285): ZabbixAPI->__callAPI()\n#2 /usr/share/zabbix/zabbix-pdf-report/inc/ZabbixAPI.class.php(100): ZabbixAPI->__login()\n#3 /usr/share/zabbix/zabbix-pdf-report/index.php(33): ZabbixAPI::login()\n#4 {main}\n  thrown in /usr/share/zabbix/zabbix-pdf-report/inc/ZabbixAPI.class.php on line 324, referer: https://zabbix-dev./zabbix-pdf-report/

Zabbix Web Version: 5.4.11

**Comment by martinm76** [comment]
Two things:
You seem to be missing curl support in your PHP installation. Find the
package that provides this and install it.

Secondly, make sure you set the version in config.inc.php to at least 5 so
it disables certain debug calls that are no longer needed and result in
extraneous output to the web page.

tor. 21. apr. 2022 16.01 skrev cflannigan ***@***.***>:

**Comment by FlanniganColum** [comment]
Thanks very much that resolved the issue only thing is reports do not show up in "Old reports" section other then that looks like its working thanks

**Comment by martinm76** [comment]
Glad to hear it.
"Old reports" can be a number of things. Are you logging in with the same login each time? I try to limit the view to those who have access to given hosts/host groups. By default Old reports are collapsed and need to be pressed to show anything. There may be interference from SELinux or similar in certain cases.

I hope you can get it resolved. I will close this issue.
