### ISSUE TITLE
Does zabbix-pdf-report work zabbix 6 ?

### ISSUE THREAD

**Issue by babsdn** [martinm76/zabbix-pdf-report#29]
Did anyone use this for zabbix 6 ? which instruction is correct for install on zabbix6?

https://github.com/martinm76/zabbix-pdf-report#readme

**Comment by martinm76** [comment]
It works with all versions I know of, at least from 4.0 onwards. You need to set $zabbix_version in config.inc.php to the version you are running. I have just committed some things that were needed for 6.2+ to work correctly with hostgroups.
