### ISSUE TITLE
Hosts Groups is empty

### ISSUE THREAD

**Issue by ahmadwasesa** [martinm76/zabbix-pdf-report#30]
![image](https://user-images.githubusercontent.com/59650450/206606633-ec828711-f229-4d8b-8ef1-45fd4a23f21e.png)

Everything is good, but not with host groups list, its empty

**Comment by ironbishop** [comment]
maybe the login failed and groups can't be read. try enabling debug and check if the login succeeds

**Comment by ahmadwasesa** [comment]
i am just editing into this, then it fix

![image](https://user-images.githubusercontent.com/59650450/206721461-afada078-0adb-4a05-a270-563051445614.png)
