### ISSUE TITLE
Chinese garbled code

### ISSUE THREAD

**Issue by yezhiyuan** [martinm76/zabbix-pdf-report#36]
when company_name is chinese, pdf report messy code
Looking forward to your reply

**Comment by martinm76** [comment]
I don't really have a way to test this myself.
I can maybe run a few tests if you provide me with some exampled that produced a messy report?

**Comment by yezhiyuan** [comment]
[10.21.12.31.pdf](https://github.com/user-attachments/files/15949203/10.21.12.31.pdf)
When I change company_name to a Chinese name, the generated PDF report becomes garbled. Similarly, when the host names contain Chinese characters, they also appear as garbled text.

**Comment by yezhiyuan** [comment]
The report contains garbled characters when there is Chinese text. Can you help me solve this problem? thank you
