### ISSUE TITLE
Question about how it works using PHP 8.1

### ISSUE THREAD

**Issue by amarodefarias** [martinm76/zabbix-pdf-report#38]
Congratulations on the project. He is truly incredible.
As some functions are deprecated, I would like to know if it is working in versions of PHP 8.1 or above?

And if not, is there a plan for this to happen?

Thank you very much

**Comment by martinm76** [comment]
I haven't tried PHP 8.1. My test server runs PHP 7.4 and works just fine with Zabbix 6.4.14.
I need someone else to give PHP 8.1 a shot.

**Comment by amarodefarias** [comment]
Hello.
Thank you very much for your feedback. I already have the version of Zabbix 6.4.14 and PHP 8.3, please can you close this question!
