### ISSUE TITLE
scheduled report with email sending

### ISSUE THREAD

**Issue by andreaconsadoriw** [martinm76/zabbix-pdf-report#4]
it's possible to create a scheduled report and send it via tools like swaks?

**Comment by habor73** [comment]
Thank you very much for building this Martin. I'd also like to be able to schedule weekly/monthly reports by email.

**Comment by jamaisx** [comment]
Hi, for a quick, really dirty solution check my repository, no enough time to write down any doc... 
https://github.com/jamaisx/zabbix-pdf-report

**Comment by psmartins** [comment]
Has anyone been able to create the reports automatically and send them by email?

**Comment by schneidr** [comment]
When calling the script via localhost it doesn't require authentication and uses credentials from the config file instead. So generate the pdf with a curl call and send it.

    curl -L -s -o /tmp/report.pdf "http://localhost/zabbix-pdf-report/createpdf.php?ReportType=hostgroup&TriggersOn=yes&GroupID=42&ReportRange=last&timePeriod=Week"
    echo "Zabbix report" | mail -s "Zabbix report" -a "From: zabbix@example.org" -A /tmp/report.pdf recipient@example.org

That's all.

**Comment by martinm76** [comment]
I can confirm that the curl solution works fine. I usually install the report to /report,so depending on how you install it, the URL needs some adjustment, but you should probably get the request from access_log anyway and adapt to curl after that.

**Comment by medrami07** [comment]
> When calling the script via localhost it doesn't require authentication and uses credentials from the config file instead. So generate the pdf with a curl call and send it.
> 
> ```
> curl -L -s -o /tmp/report.pdf "http://localhost/zabbix-pdf-report/createpdf.php?ReportType=hostgroup&TriggersOn=yes&GroupID=42&ReportRange=last&timePeriod=Week"
> echo "Zabbix report" | mail -s "Zabbix report" -a "From: zabbix@example.org" -A /tmp/report.pdf recipient@example.org
> ```
> 
> That's all.

Hey sir , please when i place this script and cron , report still dosent sent automatically
any modifications?

**Comment by schneidr** [comment]
> > When calling the script via localhost it doesn't require authentication and uses credentials from the config file instead. So generate the pdf with a curl call and send it.
> > ```
> > curl -L -s -o /tmp/report.pdf "http://localhost/zabbix-pdf-report/createpdf.php?ReportType=hostgroup&TriggersOn=yes&GroupID=42&ReportRange=last&timePeriod=Week"
> > echo "Zabbix report" | mail -s "Zabbix report" -a "From: zabbix@example.org" -A /tmp/report.pdf recipient@example.org
> > ```
> > That's all.
> 
> Hey sir , please when i place this script and cron , report still dosent sent automatically
> any modifications?

Sorry, can't help you without knowing anything about your setup. Maybe [this helps you](https://serverfault.com/questions/449651/why-is-my-crontab-not-working-and-how-can-i-troubleshoot-it). If not, feel free to ask a question on SF.
