### ISSUE TITLE
Zabbix 4.0 + PDF report 1.1.1

### ISSUE THREAD

**Issue by Ctpry** [martinm76/zabbix-pdf-report#5]
I cannot create PDF with only Host Group? It always wants host also to be selected. How to fix that problem?

**Comment by kirkwor** [comment]
Check the file chooser.php and link the css and js files properly to the files in the css/, js/ folders, should work after that.

**Comment by Ctpry** [comment]
> Check the file chooser.php and link the css and js files names properly to the files existing in the css/, js/ folders, should work after that.
files @ /usr/share/zabbix/reports/css
/usr/share/zabbix/reports/js

Page is working fine. My chooser.php about css/js texts:

<head>
        <meta http-equiv="X-UA-Compatible" content="IE=Edge"/>
        <title>Zabbix Dynamic PDF Report</title>
        <meta charset="utf-8" />
        <link rel="shortcut icon" href="/zabbix/images/general/zabbix.ico" />
        <link rel="stylesheet" type="text/css" href="css/zabbix.default.css" />
        <link rel="stylesheet" type="text/css" href="css/zabbix.color.css" />
        <link rel="stylesheet" type="text/css" href="css/zabbix.report.css" />
        <link rel="stylesheet" type="text/css" href="css/jquery.datetimepicker.min.css"/ >
        <link rel="stylesheet" type="text/css" href="css/jquery.tablesorter.pager.min.css"/ >
        <link rel="stylesheet" type="text/css" href="css/select2.css"/ >
        <script type="text/javascript" src="js/jquery-3.3.1.min.js"></script>
        <script type="text/javascript" src="js/jquery.datetimepicker.min.js"></script>
        <script type="text/javascript" src="js/jquery.validate.min.js"></script>
        <script type="text/javascript" src="js/jquery.tablesorter.combined.min.js"></script>
        <script type="text/javascript" src="js/select2.min.js"></script>
        <script>

**Comment by Ctpry** [comment]
<meta charset="utf-8" />
        <link rel="shortcut icon" href="/zabbix/images/general/zabbix.ico" />
        <link rel="stylesheet" type="text/css" href="css/zabbix.default.css" />
        <link rel="stylesheet" type="text/css" href="css/zabbix.color.css" />
        <link rel="stylesheet" type="text/css" href="css/zabbix.report.css" />
        <link rel="stylesheet" type="text/css" href="css/jquery.datetimepicker.min.css"/ >
        <link rel="stylesheet" type="text/css" href="css/jquery.tablesorter.pager.min.css"/ >
        <link rel="stylesheet" type="text/css" href="css/select2.css"/ >
        <script type="text/javascript" src="js/jquery-3.3.1.min.js"></script>
        <script type="text/javascript" src="js/jquery.datetimepicker.min.js"></script>
        <script type="text/javascript" src="js/jquery.validate.min.js"></script>
        <script type="text/javascript" src="js/jquery.tablesorter.combined.min.js"></script>
        <script type="text/javascript" src="js/select2.min.js"></script>
        <script>

**Comment by kirkwor** [comment]
try this one:

**Comment by Ctpry** [comment]
[chooser.php.txt](https://github.com/martinm76/zabbix-pdf-report/files/2935784/chooser.php.txt)
Heres better copy-paste of those lines

**Comment by martinm76** [comment]
I have fixed the javascript issues and various other in v1.2.0.
I still have issues with getting a nicely styled datepicker, but the basic one that shows up now works, at least.
You should only be able to choose a host OR a host group.
