### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by Rodce** [martinm76/zabbix-pdf-report#7]
reporter doesn't work on zabbix 4.0.5 + php7.2(3)
Right now I setup zabbix on docker (zabbix 4.2 + php7.2) and I see similar problem.

screen from zabbix 4.2
![image](https://user-images.githubusercontent.com/16733881/55463674-3a53bb00-5602-11e9-8f0c-9dc3f747f5bb.png)

**Comment by Rodce** [comment]
when I change url from  $z_server       = 'http://127.0.0.1/zabbix'; to = 'http://127.0.0.1/';
I see that
![image](https://user-images.githubusercontent.com/16733881/55468442-08dfed00-560c-11e9-8842-771d8adb8776.png)

**Comment by Rodce** [comment]
Zabbix 3.4 + php 7.2 works

![image](https://user-images.githubusercontent.com/16733881/55470823-151a7900-5611-11e9-9c9a-710b4f1eccdd.png)

**Comment by kirkwor** [comment]
Have you checked https://github.com/martinm76/zabbix-pdf-report/issues/5 for js/css being loaded properly?

**Comment by Rodce** [comment]
In this case it was't  help
For the test you can create Dockerfile
##############
FROM zabbix/zabbix-appliance:ubuntu-4.2-latest
WORKDIR /usr/share/zabbix
RUN apt-get update -y
RUN apt-get install git -y
RUN apt-get install php-curl php-json -y
RUN git clone https://github.com/martinm76/zabbix-pdf-report.git
RUN cd zabbix-pdf-report && sh fixrights.sh && mv config.inc.php.dist config.inc.php
RUN sed -i 's/https:\/\/YourServerHere\/zabbix/http:\/\/localhost/' /usr/share/zabbix/zabbix-pdf-report/config.inc.php
RUN sed -i 's/YourPasswordHere/zabbix/' /usr/share/zabbix/zabbix-pdf-report/config.inc.php
EXPOSE 80
#####################


# then 
docker build -t zabbix_4.2 .
docker run --name zabbix -p 80:80 -d zabbix_4.2

# end go to browser
http://localhost/zabbix-pdf-report/

#For do some changes on container
 docker exec -it zabbix_4.2 /bin/bash

**Comment by AngelSan19** [comment]
i have a problem, don't login ,somebody have same problem?

**Comment by martinm76** [comment]
Please try the new v1.2.0 - Not sure why, but cURL debugging was active in index.php, chooser.php and createpdf.php, which is now disabled by default, as well as updates to javascript includes and various other minor fixes.
