### ISSUE TITLE
can't create pdf file with zabbix 3.0

### ISSUE THREAD

**Issue by hayeswu** [martinm76/zabbix-pdf-report#8]
**it show below when loggin:**
2019/05/16 12:13:00 [error] 13635#0: *232 open() "/usr/share/nginx/html/zabbix_report/js/jquery.tablesorter.combined.min.js" failed (2: No such file or directory), client: 47.52.23.216, server: _, request: "GET /zabbix_report/js/jquery.tablesorter.combined.min.js HTTP/1.1", host: "139.217.3.103", referrer: "http://139.217.3.103/zabbix_report/chooser.php"
2019/05/16 12:13:00 [error] 13635#0: *233 open() "/usr/share/nginx/html/zabbix_report/js/jquery.datetimepicker.min.js" failed (2: No such file or directory), client: 47.52.23.216, server: _, request: "GET /zabbix_report/js/jquery.datetimepicker.min.js HTTP/1.1", host: "139.217.3.103", referrer: "http://139.217.3.103/zabbix_report/chooser.php"
2019/05/16 12:13:00 [error] 13635#0: *234 open() "/usr/share/nginx/html/zabbix_report/css/jquery.tablesorter.pager.min.css" failed (2: No such file or directory), client: 47.52.23.216, server: _, request: "GET /zabbix_report/css/jquery.tablesorter.pager.min.css HTTP/1.1", host: "139.217.3.103", referrer: "http://139.217.3.103/zabbix_report/chooser.php"
2019/05/16 12:13:00 [error] 13635#0: *235 open() "/usr/share/nginx/html/zabbix_report/js/jquery-3.3.1.min.js" failed (2: No such file or directory), client: 47.52.23.216, server: _, request: "GET /zabbix_report/js/jquery-3.3.1.min.js HTTP/1.1", host: "139.217.3.103", referrer: "http://139.217.3.103/zabbix_report/chooser.php"
2019/05/16 12:13:01 [error] 13635#0: *234 open() "/usr/share/nginx/html/zabbix_report/js/jquery.datetimepicker.min.js" failed (2: No such file or directory), client: 47.52.23.216, server: _, request: "GET /zabbix_report/js/jquery.datetimepicker.min.js HTTP/1.1", host: "139.217.3.103", referrer: "http://139.217.3.103/zabbix_report/chooser.php"
2019/05/16 12:13:01 [error] 13635#0: *234 open() "/usr/share/nginx/html/zabbix_report/js/jquery.tablesorter.combined.min.js" failed (2: No such file or directory), client: 47.52.23.216, server: _, request: "GET /zabbix_report/js/jquery.tablesorter.combined.min.js HTTP/1.1", host: "139.217.3.103", referrer: "http://139.217.3.103/zabbix_report/chooser.php"

**Comment by martinm76** [comment]
Hey there.
There were some references that were wrong in the last commit 2 years ago with regards to javascript files, etc.
I have just released v1.2.0 where I have fixed several mostly minor things and tested the report on Zabbix 5.0
Also check if SELinux is enabled. It requires extra setup. I have commented a bit on this in the readme.
